title: Sightreading Academy
description: Master sight-reading and music theory
theme: minima
baseurl: "/sightreadingacademy"
url: "https://siavashsed.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
